using System.Collections.Generic;

namespace Fricke_ITM_325_Assignment_4.Code
{
    public class WordCollection
    {
        public static readonly WordCollection Instance = new WordCollection();

        public List<string> words = new List<string>()
        {
            "apple",
            "banana",
            "cherry",
            "elderberry",
            "grape",
            "honeydew",
            "lemon",
            "mango",
            "nectarine",
            "orange",
            "papaya",
            "quince",
            "raspberry",
            "strawberry",
            "tangerine",
            "voavanga",
            "watermelon",
            "xigua",
            "yangmei",
            "zucchini",
            "aluminium",
            "structure",
            "prisoner",
            "management",
            "residence",
            "hardship",
            "childish",
            "illusion",
            "perform",
            "freighter",
            "possibility",
            "haunt",
            "storage",
            "lighter",
            "laundry",
            "organisation",
            "appeal",
            "venture",
            "appearance",
            "association",
            "legislation",
            "cooperate",
            "cycle",
            "plane",
            "sensitive",
            "cunning",
            "prejudice",
            "pyramid",
            "miracle",
            "penny",
            "confuse",
            "drama",
            "dictate",
            "withdrawal",
            "soprano",
            "moral",
            "symptom",
            "troop",
            "specimen",
            "business",
            "divide",
            "vigorous",
            "active",
            "ample",
            "dominant",
            "humor",
            "water",
            "therapist",
            "agreement",
            "alive",
            "assessment",
            "knowledge",
            "direct",
            "leash",
            "voter",
            "confuse",
            "twist",
            "steak",
            "contact",
            "extort",
            "suntan",
            "tower",
            "kitchen",
            "telephone",
            "thought",
            "camera",
            "shrink",
            "X-ray",
            "exclusive",
            "misery",
            "driver",
            "skate",
            "advantage",
            "projection",
            "share",
            "brick",
            "thank",
            "comfort"
        };

        public Dictionary<string, string> responses = new Dictionary<string, string>
        {
            { "Correct", "Nice work, you got a correct letter." },
            { "Incorrect", "Sorry, try again." },
            { "Start", "Try guessing a missing letter from the word shown." },
            { "Win", "Win! Solution: {0}. Remaining guesses: {1}. Enter ! to start a new game." },
            { "Lose", "Lose! Solution: {0}. Remaining guesses: {1}. Enter ! to start a new game." },
            { "GameOver", "Game over. Enter ! to start a new game." },
            { "RepeatGuess", "You already guessed '{0}'." }
        };
    }
}
